// <auto-generated />
namespace UserAuth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class getHousetablescript : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(getHousetablescript));
        
        string IMigrationMetadata.Id
        {
            get { return "202405130641130_get House table script"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
